#!/usr/bin/zsh

function run_100ms_tasks ()
{
    echo 100ms_task  
}

function run_1s_tasks ()
{
    echo 1s_task 
}

function run_5s_tasks ()
{
    echo 5s_task
}

while true 
do
    tick_100ms=$tick_100ms+1
    run_100ms_tasks

    if [[ $tick_100ms -eq 10 ]]
    then
        tick_1s=$tick_1s+1
        tick_100ms=0
        run_1s_tasks 

        if [[ $tick_1s -eq 5 ]]
        then
            tick_1s=0
            run_5s_tasks
        fi 
    fi
    sleep 0.1
done

