#!/bin/zsh
_GROUP_IP1='ff05::2'

gst-launch-1.0 -v udpsrc multicast-group=$_GROUP_IP1 auto-multicast=true multicast-iface='eth0' caps = 'application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)96' ! rtph264depay ! h264parse ! avdec_h264 ! videobalance brightness=0.0 contrast=1.0 hue=0.0 saturation=1.5 ! videoconvert ! autovideosink sync=false
#gst-launch-1.0 -v videomixer name=mixer ! autovideosink sync=false ! udpsrc multicast-group=$_GROUP_IP1 auto-multicast=true caps = 'application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)96' ! rtph264depay ! h264parse ! avdec_h264 ! videobalance brightness=0.0 contrast=1.0 hue=0.0 saturation=1.5 ! videoconvert ! mixer. \
