#!/usr/bin/zsh 
_state=INIT  		# INIT,FRONT,BACK,BOTTOM,ERROR

_front_ms=0
_back_ms=0
_bottom_ms=0
_error_ms=0

_front_time=0:00:00:00.000
_back_time=0:00:00:00.000
_bottom_time=0:00:00:00.000
_error_time=0:00:00:00.000

_last=0
_difference=0


convert_to_ms()
{
  read -r d h m s ms <<< $(echo $1 | tr '.:' ' ' )
  echo $(((d*24*60*60*1000)+(h*60*60*1000)+(m*60*1000)+(s*1000)+(ms)))
}
convert_to_time () 
{ 
    _ms=$1
 
    # Calculate days 
    _days=$(printf "%u\n" $(($_ms/(24*60*60*1000)))) 
    _ms=$(($_ms-($_days*24*60*60*1000))) 
    _days=$(printf "%u" $_days) 
 
    # Calculate hours 
    _hours=$(printf "%u\n" $(($_ms/(60*60*1000)))) 
    _ms=$(($_ms-($_hours*60*60*1000))) 
    _hours=$(printf "%02u" $_hours) 
 
    # Calculate minutes 
    _min=$(printf "%u\n" $(($_ms/(60*1000)))) 
    _ms=$(($_ms-($_min*60*1000))) 
    _min=$(printf "%02u" $_min) 
 
    # Calculate seconds 
    _sec=$(printf "%u\n" $(($_ms/1000))) 
    _ms=$(($_ms-($_sec*1000))) 
    _sec=$(printf "%02u" $_sec) 
 
    # Calculate tenths 
    _ms=$(printf "%03u" $_ms) 
 
   echo "${_days}:${_hours}:${_min}:${_sec}.${_ms}" 
}
