#!/bin/bash

# Create fifos
mkfifo /tmp/fifo1
mkfifo /tmp/fifo2

# Show data from fifos
cat <> /tmp/fifo1 &
PIDS+=$!
cat <> /tmp/fifo2 &
PIDS+=$!

# Generate data in fifos
while true; do
	sleep 1
	echo test > /tmp/fifo1
done &
PIDS+=$!

while true; do
	sleep 1
	echo test > /tmp/fifo2
done &
PIDS+=$!

# Set trap
trap "kill -KILL ${PIDS[*]};rm /tmp/fifo1;rm /tmp/fifo2" SIGINT

# Wait for SIGINT
wait
