#!/bin/bash

# Start threads
while true
do
        _timestamp=$(date +%T)
        _temperature=$(python ~/bin/get_temperature.py)
        _humidity=$(python ~/bin/get_humidity.py)
        echo $_timestamp','$_temperature','$_humidity
        sleep 10
done

