#!/bin/bash

# Create fifos
mkfifo /tmp/fifo1
mkfifo /tmp/fifo2

# Open fifos as RW to make sure they remain open
exec 3<>/tmp/fifo1
exec 4<>/tmp/fifo2

# Show data from fifos
cat /tmp/fifo1 &
PIDS[0]=$!
cat /tmp/fifo2 &
PIDS[1]=$!

# Generate data in fifos
while true; do
	data=$(( RANDOM % 10 ))
        echo New random number: $data	

	if [[ $data -lt 5 ]]; then
		echo Fifo 1: $data >&3
	else
		echo Fifo 2: $data >&4
	fi

	sleep 1
done &

PIDS[2]=$!

# Set trap
trap "kill -KILL ${PIDS[*]};rm /tmp/fifo1;rm /tmp/fifo2" SIGINT

# Wait for SIGINT
wait
