#!/usr/bin/zsh

# Create fifos
mkfifo /tmp/fifo1
mkfifo /tmp/fifo2

# Show data from fifos
cat /tmp/fifo1 &
PIDS+=$!
cat /tmp/fifo2 &
PIDS+=$!

# Generate data in fifos
while true; do
	data=$(( RANDOM % 10 )) 

	if [[ $data -lt 5 ]]; then
		sleep 1
		printf "Fifo 1: %s\n" "$data" > /tmp/fifo1
	else
		sleep 1
		printf "Fifo 2: %s\n" "$data" > /tmp/fifo1
	fi
done &

PIDS+=$!

# Set trap
trap "kill -KILL ${PIDS[*]}" SIGINT

# Wait for SIGINT
wait
