#!/usr/bin/zsh -x
# 
# Script for communicating with the ATOS system
# Author Leon Bonde Larsen <leon@bondelarsen.dk>
#

run_command ()
# All calls are made through this function in order to allow dryrun
{
	if [ $_DRYRUN = true ]; then
		echo "$*"
		return 0
	fi

	eval "$@"
}

print_error ()
# Outputs error messages
{
	>&2 echo $1
	exit 0
}

exit_SIGINT () 
{
	print_error 'Exiting due to SIGINT'
}

usage() 
{
	print_error "
	usage: ${0##*/} [OPTIONS] unit|all [COMMAND] 

	Communicate with the ATOS system (Artificial Tutoring Of Songbirds)

	OPTIONS
	-d       Dry run. Echoes commands instead of running them.
	-v       Verbose. Outputs all information.

	COMMANDS
	ssh      Connect via ssh
	net      Setup internet gateway
	start    Start unit
	stop     Stop unit
	nop      Do nothing
	"
}

send_ssh()
# Execute command-line on remote machine via ssh
{
	run_command ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t -t ${_REMOTE_USER}@${_REMOTE_IP} "$@"
}

send_tmux()
# Execute command-line on remote machine in tmux startup-session 
{
	send_ssh "tmux send-keys -t startup:0.0 $@" 
}

setup_environment()
# Set environment variables based on _UNIT variable
{
	if [[ -e $_ATOS_PATH${_UNIT}/_env ]]; then
		source ${_ATOS_PATH}${_UNIT}/_env
		_REMOTE_IP=$(avahi-resolve-host-name -6 ${_REMOTE_HOST}.local | cut -f2)

		if [ -e ${_ATOS_PATH}bin/_${_COMMAND} ]; then

			echo "Running $_COMMAND on $_UNIT..."
			source ${_ATOS_PATH}bin/_${_COMMAND}
		else
			print_error 'Unknown command!'
			usage
		fi
	else
		print skipping unknown unit: $_UNIT
		#print_error 'Unit not found'
	fi
}


setup_and_execute()
# Setup environment and execute command
{

	case $_COMMAND in
		'ssh')
			setup_environment 
			;;
		*)
			{
				setup_environment 
			} 1> >(logger -s -t ats.$_UNIT) 2>&1
	esac
}

# Set default options
_DRYRUN=false

# Parse options
while getopts "dv" opt; do
	case "$opt" in
		d)  echo 'Dry run mode!';_DRYRUN=true      ;;
		v) set -x ;;
	esac
done
shift $(( OPTIND - 1 )); OPTIND=1

# Set script options
set -o errexit
set -o nounset

# Signal trapping
trap exit_SIGINT SIGINT

# Set variables
_ATOS_PATH=${0%/*}/
_COMMAND=$2
_UNIT=$1

# Set global variables
source $_ATOS_PATH/global_settings

if [ $_UNIT = 'all' ]; then
	for _UNIT in $(avahi-browse -lart | $_ATOS_PATH/bin/avahi-list _iface=$_IFACE | cut -d'.' -f1); do 
		setup_and_execute
        done	       
else
	setup_and_execute
fi



