#!/bin/bash

export SENSOR_POLL_PERIOD={{ sensor_poll_period }}
export CAGE={{ cage }}
export FRONT_GPIO_PATH={{ front_gpio_path }}
export BACK_GPIO_PATH={{ back_gpio_path }}

{{ remote_services_path }}/{{ node_name }}/bin/export_gpios

exec {{ remote_services_path }}/{{ node_name }}/bin/gpio_streamer
