#!/bin/bash

#_GROUP_IP='224.0.0.100'
_GROUP_IP='ff05::2'
# ff75::1

gst-launch-1.0 -e -v v4l2src do-timestamp=true ! video/x-raw,width=800,height=480,framerate=30/1 ! omxh264enc ! rtph264pay config-interval=1 ! udpsink host=$_GROUP_IP auto-multicast=true

#gst-launch-1.0 videotestsrc ! x264enc ! rtph264pay config-interval=1 ! udpsink host=$_GROUP_IP auto-multicast=true

