#  
# Node
#

- name: Configure node 
  include_role:
    name: base_node 
  vars:
      node_name: "node"
      node_description: "Temperature, Humidity and pressure event emitter"
      remote_services_path: "/home/pi/Services"
      local_bin_path: bin
      services: 
      - name: "temperature"
        template: templates/service

- name: "(Re)start node"
  svc:
    name: "temperature"
    service_dir: "/etc/service/"
    state: restarted

