---
- name: 'include os-specific vars'
  include_vars: "{{ansible_os_family | lower }}.yml"
  tags:
    - 'chrony'
    - 'chrony-vars'

- include: "install_{{ ansible_os_family | lower}}.yml"
- include: "configure.yml"
- include: "service.yml"
