# ansible_user is defined in inventory

#- name: Update repositories cache and install "kafkacat" package
#  apt:
#    name: kafkacat
#    update_cache: yes

- name: "Setup service status service"
  cron:
    name: "Run status service every minute"
    job: "/usr/bin/svc -o /etc/service/status/"

- name: Configure node 
  include_role:
    name: base_node 
  vars:
      node_name: "status_node"
      node_description: "Status node"
      remote_services_path: "/home/{{ ansible_user }}/Services"
      local_bin_path: bin 
      services: 
      - name: "status"
        template: templates/service

- name: Stop service
  svc:
    name: status
    state: stopped
    service_dir: /etc/service

- name: Make sure service stays down after reboot
  file:
    path: /home/{{ ansible_user }}/Services/status_node/status/down
    state: touch
