#!/bin/bash

# Setup GPIOs
echo 17 > /sys/class/gpio/export
sleep 2
echo in > /sys/class/gpio17/direction

echo 27 > /sys/class/gpio/export
sleep 2
echo in > /sys/class/gpio27/direction

# Start threads
while true;do sleep 60;python ~/bin/get_temperature.py;done | gst-launch-1.0 -e -v fdsrc ! "text/x-raw" ! udpsink host=$ATS_MONITOR02_TEMPERATURE_IP auto-multicast=true &
PIDS[0]=$!

while true;do sleep 60;python ~/bin/get_pressure.py;done | gst-launch-1.0 -e -v fdsrc ! "text/x-raw" ! udpsink host=$ATS_MONITOR02_PRESSURE_IP auto-multicast=true &
PIDS[1]=$!

while true;do sleep 60;python ~/bin/get_humidity.py;done | gst-launch-1.0 -e -v fdsrc ! "text/x-raw" ! udpsink host=$ATS_MONITOR02_HUMIDITY_IP auto-multicast=true &
PIDS[2]=$!

while true;do sleep 1;_p1=$(cat /sys/class/gpio/gpio17/value);_p2=$(cat /sys/class/gpio/gpio27/value);echo $_p1,$_p2;done | gst-launch-1.0 -e -v fdsrc ! "text/x-raw" ! udpsink host=$ATS_MONITOR02_PERCH_IP auto-multicast=true &
PIDS[3]=$!



# Trap and kill all threads
trap "kill -KILL ${PIDS[*]}" SIGINT

wait




