#!/bin/zsh
#source /home/leon/Documents/scripts/ats/global_settings 
_AUDIO_CAPS='application/x-rtp, media=audio, clock-rate=48000, encoding-name=L16, encoding-params=1, payload=96, format=S16BE, rate=48000, channels=1, layout=interleaved'

# Decode and mix as stereo (box1 in left and box2 in right)
#gst-launch-1.0 -v -m udpsrc multicast-group=$ATS_BOX2_MIC_IP multicast-iface=$_IFACE auto-multicast=true caps=$_AUDIO_CAPS ! rtpL16depay ! audioconvert ! queue ! interleave name=mix ! autoaudiosink 

# Decode and mix as stereo (box1 in left and box2 in right)
#gst-launch-1.0 -v interleave name=mix ! autoaudiosink \
	#udpsrc multicast-group=ff15::11 multicast-iface=eth0 auto-multicast=true caps=$_AUDIO_CAPS ! rtpL16depay ! audioconvert ! queue ! mix. \
	#udpsrc multicast-group=ff15::12 multicast-iface=eth0 auto-multicast=true caps=$_AUDIO_CAPS ! rtpL16depay ! audioconvert ! queue ! mix.

gst-launch-1.0 -v udpsrc multicast-group=ff15::12 multicast-iface=eth0 auto-multicast=true caps=$_AUDIO_CAPS ! rtpL16depay ! audioconvert ! queue ! autoaudiosink 
