#!/bin/zsh

gst-launch-1.0 -ve filesrc location="/home/leon/recordings/fake1.ogg" ! oggdemux name=d d. ! queue ! theoradec ! videoconvert ! autovideosink d. ! queue ! flacdec ! audioconvert ! autoaudiosink

#autoconvert ! theoradec ! videoconvert ! autovideosink sync=false \

#gst-launch-1.0 -vm multifilesrc location="/home/leon/recordings/test%d.ogg" index=0 caps="application/ogg, framerate=30/1" ! oggdemux name=d \
#gst-launch-1.0 -vm filesrc location="/home/leon/recordings/fake1.ogg" ! fakesink ! oggdemux name=d d.! fakesink 
#d. ! queue ! flacdec ! audioconvert ! autoaudiosink
