#!/bin/zsh
_IIB1_AUDIO='ff05::3'
_IIB2_AUDIO='ff05::4'
_AUDIO_CAPS='application/x-rtp, media=audio, clock-rate=44100, encoding-name=L16, encoding-params=1, payload=96, format=S16BE, rate=44100, channels=1, layout=non-interleaved'

_IIB1_VIDEO='ff05::1'
_IIB2_VIDEO='ff05::2'
_VIDEO_CAPS='application/x-rtp, media=video, clock-rate=90000, encoding-name=H264, payload=96, format=I444, framerate=25/1, width=800, height=480, interlace-mode=progressive, pixel-aspect-ratio=1/1'


gst-launch-1.0 -e -v \
  oggmux name=oggmix ! "application/ogg" ! queue2 ! "application/ogg" ! shout2send ip=192.168.100.102 port=8000 password=pass mount=/icecast/test.ogv \
  interleave name=audiomix ! audioparse ! "audio/x-raw, rate=44100, format=S16LE,channels=2, layout=interleaved" ! flacenc ! "audio/x-flac, channels=2, rate=44100" ! queue2 ! oggmix. \
      udpsrc multicast-group=$_IIB1_AUDIO multicast-iface='eth0' auto-multicast=true caps=$_AUDIO_CAPS ! rtpL16depay ! audioconvert ! "audio/x-raw, rate=44100, format=S16LE,channels=1, layout=interleaved" ! queue2 ! audiomix. \
      udpsrc multicast-group=$_IIB2_AUDIO multicast-iface='eth0' auto-multicast=true caps=$_AUDIO_CAPS ! rtpL16depay ! audioconvert ! "audio/x-raw, rate=44100, format=S16LE,channels=1, layout=interleaved" ! queue2 ! audiomix. \
      videomixer name=videomix sink_1::ypos=480 ! videoconvert ! "video/x-raw, format=I420, width=800, height=960, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=bt709, framerate=25/1" ! videoparse framerate=25/1 width=800 height=960 interlaced=true format=2 ! "video/x-raw, format=I420, width=800, height=960, pixel-aspect-ratio=1/1, interlace-mode=interleaved, colorimetry=bt709, framerate=25/1" ! theoraenc ! queue2 ! oggmix. \
    udpsrc multicast-group=$_IIB1_VIDEO auto-multicast=true multicast-iface='eth0' caps=$_VIDEO_CAPS ! rtph264depay ! "video/x-h264, stream-format=byte-stream, stream-format=avc, alignment=au, profile=high, level=4" ! h264parse ! avdec_h264 ! "video/x-raw, format=I420, width=800, height=480, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=bt601, framerate=25/1" ! videoconvert ! "video/x-raw, framerate=25/1, width=800, height=480" ! queue2 ! "video/x-raw, format=I420, width=800, height=480, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=bt601, framerate=25/1" ! videomix. \
      udpsrc multicast-group=$_IIB2_VIDEO auto-multicast=true multicast-iface='eth0' caps=$_VIDEO_CAPS ! rtph264depay ! "video/x-h264, stream-format=byte-stream, stream-format=avc, alignment=au, profile=high, level=4" ! h264parse ! avdec_h264 ! "video/x-raw, format=I420, width=800, height=480, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=bt601, framerate=25/1" ! videoconvert ! "video/x-raw, framerate=25/1, width=800, height=480" ! queue2 ! videomix.

# "video/x-raw, format=Y444, framerate=30/1, width=800, height=960, interlace-mode=progressive, pixel-aspect-ratio=1/1"
# "video/x-theora, width=800, height=960, pixel-aspect-ratio=1/1, framerate=25/1"
# "video/x-raw, format=I420, width=800, height=960, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=bt709, framerate=25/1"
