#!/bin/zsh
_IIB1_AUDIO='ff05::3'
_IIB2_AUDIO='ff05::4'
_AUDIO_CAPS='application/x-rtp, media=audio, clock-rate=44100, encoding-name=L16, encoding-params=1, payload=96, format=S16BE, rate=44100, channels=1, layout=non-interleaved'

_IIB1_VIDEO='ff05::1'
_IIB2_VIDEO='ff05::2'
_VIDEO_CAPS='application/x-rtp, media=video, clock-rate=90000, encoding-name=H264, payload=96, format=I444, framerate=25/1, width=800, height=480, interlace-mode=progressive, pixel-aspect-ratio=1/1'

# oggmix caps
_A01="application/ogg" 
_A02="application/ogg" 

# audiomix caps
_B01=
_B02="audio/x-raw, rate=44100, format=S16LE,channels=2, layout=interleaved"
_B03="audio/x-flac, channels=2, rate=44100"

# audio receive caps
_C01=
_C02=
_C03="audio/x-raw, rate=44100, format=S16LE,channels=1, layout=interleaved"

# videomix caps
_D01=
_D02="video/x-raw, format=I420, width=800, height=960, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=bt709, framerate=25/1"
_D03="video/x-raw, format=I420, width=800, height=960, pixel-aspect-ratio=1/1, interlace-mode=interleaved, colorimetry=bt709, framerate=25/1"
_D04=

# video receive caps
_E01=
_E02="video/x-h264, stream-format=byte-stream, stream-format=avc, alignment=au, profile=high, level=4"
_E03=
_E04="video/x-raw, format=I420, width=800, height=480, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=bt601, framerate=25/1"
_E05="video/x-raw, framerate=25/1, width=800, height=480"
_E06="video/x-raw, format=I420, width=800, height=480, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=bt601, framerate=25/1"

gst-launch-1.0 -e -v \
  oggmux name=oggmix ! $_A01 ! queue2 ! $_A02 ! multifilesink post-messages=true next-file=4 max-file-size=1000000 location=/home/leon/recordings/fake%d.ogg \
\
  interleave name=audiomix ! audioparse ! $_B02 ! flacenc ! $_B03 ! queue2 ! oggmix. \
\
  audiotestsrc ! audioconvert ! $_C03 ! queue2 ! audiomix. \
  audiotestsrc ! audioconvert ! $_C03 ! queue2 ! audiomix. \
\ 
  videomixer name=videomix sink_1::ypos=480 ! videoconvert ! $_D02 ! videoparse framerate=25/1 width=800 height=960 interlaced=true format=2 ! $_D03 ! theoraenc ! $_D04 ! queue2 ! oggmix. \
\
  videotestsrc ! videoconvert ! $_E05 ! queue2 ! $_E06 ! videomix. \
  videotestsrc ! videoconvert ! $_E05 ! queue2 ! $_E06 ! videomix.

# "video/x-raw, format=Y444, framerate=30/1, width=800, height=960, interlace-mode=progressive, pixel-aspect-ratio=1/1"
# "video/x-theora, width=800, height=960, pixel-aspect-ratio=1/1, framerate=25/1"
# "video/x-raw, format=I420, width=800, height=960, pixel-aspect-ratio=1/1, interlace-mode=progressive, colorimetry=bt709, framerate=25/1"
