#!/bin/bash

export _VIDEO_CAPS='application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)96'
export MG_IP={{ multicast_group }}
export DISPLAY={{ display }}

export _brightness={{ brightness }}
export _contrast={{ contrast }}
export _hue={{ hue }}
export _saturation={{ saturation }}
export _flip={{ flip }}

exec ../bin/display_video 
