#!/bin/bash

gst-launch-1.0 -e -v v4l2src io-mode=2 do-timestamp=true brightness=$BRIGHTNESS contrast=$CONTRAST hue=$HUE saturation=$SATURATION  ! "video/x-raw,width=800,height=480,framerate=$FRAME_RATE" ! omxh264enc ! "video/x-h264, format=I444, framerate=$FRAME_RATE, width=800, height=480, interlace-mode=progressive, pixel-aspect-ratio=1/1" ! rtph264pay config-interval=1 ! udpsink host=$ATS_BOX1_CAM_IP auto-multicast=true
