- hosts: microphone-array-box  
  roles:
  - role: microphone_array_node
    vars:
      multicast_group: "ff15::12"
      type: "audio"
      id: 12
      channel1:
        multicast_group: "ff15::11"
      channel2:
        multicast_group: "ff15::12"

