# From setup_birdpis.yml
- hosts: all
  tasks:
    - name: Remove "network-manager" package
      apt:
        name: network-manager
        state: absent

    - name: Installs repository
      apt_repository:
        repo: deb http://vontaene.de/raspbian-updates/ . main
        state: present
        filename: 'gstreamer-omx'

    - name: Runs apt update and installs gstreamer-omx
      apt:
         update_cache: yes
         allow_unauthenticated: yes
         name: gstreamer1.0-omx

# From chrony_birdpis.yml
    - name: remove ntp 
      apt: name=ntp state=absent

    - name: enable service ntp and ensure it is not masked
      systemd:
        name: ntp 
        enabled: no
        masked: no
  roles:
    - role: chrony
      vars: 
      chrony_server: 'fd5d:beef:beef:beef::1 iburst minpoll 8'

