# multicast group convention:
#   prefix ff15::
#   video 1-9
#   audio 11-19
#   events 20

 
# The output boxes have multiple nodes running on them
- hosts: leon-office-monitor-box
  roles: 
  - role: display_node
    vars:
      multicast_group: "ff15::2"
      id: 0
      type: "video output"
      display: ":0.0"
      brightness: "0.2"
      contrast: "1.0"
      hue: "0.0"
      saturation: "1.0"
      flip: "rotate-180"








