#!/bin/bash

# Setup GPIOs
echo 17 > /sys/class/gpio/export
echo in > /sys/class/gpio17/direction

echo 27 > /sys/class/gpio/export
echo in > /sys/class/gpio27/direction

# Start threads
while true;do sleep 60;python ~/bin/get_temperature.py;done | gst-launch-1.0 -e -v fdsrc ! "text/x-raw" ! udpsink host=$ATS_MONITOR01_TEMPERATURE_IP auto-multicast=true &
PIDS[0]=$!

while true;do sleep 60;python ~/bin/get_pressure.py;done | gst-launch-1.0 -e -v fdsrc ! "text/x-raw" ! udpsink host=$ATS_MONITOR01_PRESSURE_IP auto-multicast=true &
PIDS[1]=$!

while true;do sleep 60;python ~/bin/get_humidity.py;done | gst-launch-1.0 -e -v fdsrc ! "text/x-raw" ! udpsink host=$ATS_MONITOR01_HUMIDITY_IP auto-multicast=true &
PIDS[2]=$!

while true;do sleep 2;cat /sys/class/gpio/gpio17/value;done | while read line;do if [[ $line -eq 0 ]];then echo on;else echo off;fi;done | gst-launch-1.0 -e -v fdsrc ! "text/x-raw" ! udpsink host=$ATS_MONITOR01_FRONT_PERCH_IP auto-multicast=true &
PIDS[3]=$!

while true;do sleep 2;cat /sys/class/gpio/gpio27/value;done | while read line;do if [[ $line -eq 0 ]];then echo on;else echo off;fi;done  | gst-launch-1.0 -e -v fdsrc ! "text/x-raw" ! udpsink host=$ATS_MONITOR01_BACK_PERCH_IP auto-multicast=true &
PIDS[4]=$!


# Trap and kill all threads
trap "kill -KILL ${PIDS[*]}" SIGINT

wait




