#  
# Node
#

- name: Configure node
  include_role:
    name: base_node
  vars:
      node_name: "speaker_node"
      node_description: "Outputs sound from stream to the speaker"
      remote_services_path: "/home/pi/Services"
      local_bin_path: bin
      services:
      - name: "speaker"
        template: templates/service
        pre_up_script: "set_speaker"
