#  
# Node
#

- name: Install the package "kafkacat"
  apt:
    name: kafkacat

- name: Configure node 
  include_role:
    name: base_node 
  vars:
      node_name: "node"
      node_description: "Template node"
      remote_services_path: "/home/pi/Services"
      local_bin_path: bin 
      services: 
      - name: "GPIO_streamer"
        template: templates/service

- name: Reboot box 
  include_role:
    name: common
    tasks_from: reboot

