#!/usr/bin/zsh
set -m
source global_settings
_IFACE=eth0

accumulator/timestamper $ATS_MONITOR01_PERCH_IP $_IFACE /tmp/m01 &
PIDS[0]=$!

accumulator/timestamper $ATS_MONITOR02_PERCH_IP $_IFACE /tmp/m02 &
PIDS[1]=$!

#trap "kill -s -SIGINT $(jobs | awk '/[0-9]/ {gsub("\\[","%");gsub("\\]","");gsub("\\+","");gsub("\\-","");print $1}' | awk '{printf("%s ", $0)}' )" SIGINT
trap "kill -SIGINT ${PIDS[@]}" SIGINT

wait
