#!/bin/bash

trap "kill -SIGINT ${PIDS[*]}" SIGINT

accumulator/start_timestampers &
PIDS[0]=$!

sleep 2

accumulator/accumulator ${_REMOTE_WORKSPACE}m01 &
PIDS[1]=$!

accumulator/accumulator ${_REMOTE_WORKSPACE}m02 &
PIDS[2]=$!

DISPLAY=:0.0 exec i3-sensible-terminal xterm -e "watch -d -t tail -n1 ${_REMOTE_WORKSPACE}m01_acc ${_REMOTE_WORKSPACE}m02_acc 2> /dev/null" 

# my_func() {
#  jobs > /tmp/dims
#  cat /tmp/dims | grep -o '[0-9]\+'
#  #jobs | grep -o '[0-9]\+' 
#  #echo $jbs
#  #kill -SIGINT $jbs
#}

#echo "kill -SIGINT $(jobs | awk -F'[][]' '{print "%"$2} END{printf "\n"} ' ORS=' ')"
#trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
#trap "killall background" SIGINT SIGTERM EXIT
#trap "kill -SIGINT $(jobs | awk '/[0-9]/ {gsub("\\[","%");gsub("\\]","");gsub("\\+","");gsub("\\-","");print $1}' | awk '{printf("%s ", $0)}' )" SIGINT

#watch -d -t tail -n1 /tmp/m0{1,2}_acc



