#!/usr/bin/zsh

ts_get_msec()
{
  read -r h m s ms <<< $(echo $1 | tr '.:' ' ' )
  echo $(((h*60*60*1000)+(m*60*1000)+(s*1000)+ms))
}

start_ts=$1
stop_ts=$2
if [[ $start_ts = $stop_ts ]] 
then
	echo 0
else
	START=$(ts_get_msec $start_ts)
	STOP=$(ts_get_msec $stop_ts)
	DIFF=$((STOP-START))
	echo $DIFF
fi
